# Generated by Django 6.0.7 on 2026-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onboard',
            field=models.BooleanField(default=False),
        ),
    ]
