# Generated by Django 6.0.7 on 2026-07-13 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_profile_is_onboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_save',
            field=models.ManyToManyField(blank=True, related_name='post_save', to=settings.AUTH_USER_MODEL),
        ),
    ]
